# Generated by Django 5.1 on 2024-08-31 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.cartitem')),
            ],
        ),
    ]
