# Generated by Django 5.1 on 2024-09-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
