# Generated by Django 5.1 on 2024-09-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_details_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.TextField(),
        ),
    ]
