# Generated by Django 5.1 on 2024-09-01 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_alter_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.details'),
            preserve_default=False,
        ),
    ]
