# Generated by Django 5.1 on 2024-09-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_details_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='customer',
        ),
    ]
