# Generated by Django 5.1 on 2024-09-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0011_details_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
