# Generated by Django 5.1 on 2024-09-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0012_details_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='quantity',
            new_name='quantityy',
        ),
    ]
