# Generated by Django 5.1 on 2024-09-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0013_rename_quantity_details_quantityy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='quantityy',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
