# Generated by Django 5.1 on 2024-09-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0014_rename_quantityy_details_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='customer',
        ),
    ]
