# Generated by Django 5.1 on 2024-09-06 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0015_remove_details_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
