# Generated by Django 5.1 on 2024-09-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0016_details_customer_payment_details_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='details',
        ),
    ]
