# Generated by Django 5.1 on 2024-09-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0017_remove_details_customer_remove_payment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
        migrations.AddField(
            model_name='payment',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.details'),
            preserve_default=False,
        ),
    ]
