# Generated by Django 5.1 on 2024-09-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0019_rename_details_payment_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='detail',
            new_name='details',
        ),
    ]
