# Generated by Django 5.1 on 2024-09-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0020_rename_detail_payment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='details',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
