# Generated by Django 5.1 on 2024-09-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0022_payment_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
    ]
