# Generated by Django 5.1 on 2024-09-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0024_payment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.products'),
        ),
    ]
