# Generated by Django 5.1 on 2024-09-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0025_alter_payment_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='item',
        ),
    ]
